version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: utkucanbiyikli
      POSTGRES_PASSWORD: qazwsx.1234
      POSTGRES_DB: sozluk_db
    ports:
      - '5432'

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py createsuperuser --email utkucanbykl@gmail.com --username utkucanbykl --first_name utku --last_name can && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/db
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db





