# Generated by Django 2.2.7 on 2019-12-06 08:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='title',
            managers=[
                ('entry_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
