# Generated by Django 2.2.7 on 2020-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200207_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', through='core.Like', to='core.Entry'),
        ),
    ]
