# Generated by Django 2.2.10 on 2020-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
