# Generated by Django 2.2.10 on 2020-03-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='entry',
        ),
        migrations.AddField(
            model_name='follow',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='core.Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', through='core.Follow', to='core.Title'),
        ),
    ]
