# Generated by Django 2.2.10 on 2020-03-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200330_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Title'),
        ),
    ]
