# Generated by Django 2.2.10 on 2020-05-01 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200501_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_vote_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
