# Generated by Django 2.2.10 on 2020-05-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200501_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='last_vote_Time',
            new_name='last_vote_time',
        ),
    ]
