# Generated by Django 2.2.10 on 2020-05-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200501_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='to_user',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='from_user',
            new_name='sender_user',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_vote_time',
        ),
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
    ]
