# Generated by Django 2.2.10 on 2020-05-01 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200501_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_vote_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
