# Generated by Django 2.2.10 on 2020-05-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='status',
        ),
        migrations.RemoveField(
            model_name='like',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
