# Generated by Django 2.2.10 on 2020-05-07 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200505_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to=settings.AUTH_USER_MODEL),
        ),
    ]
