# Generated by Django 2.2.10 on 2020-05-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200508_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='core.Title'),
        ),
    ]
