# Generated by Django 2.2.10 on 2020-05-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200512_1947'),
        ('core', '0029_auto_20200508_2030'),
    ]

    operations = [
    ]
