# Generated by Django 2.2.13 on 2020-08-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20200512_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dislike',
            constraint=models.UniqueConstraint(fields=('user', 'entry'), name='dislike_unique'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'entry'), name='like_unique'),
        ),
    ]
