# Generated by Django 2.2.13 on 2020-08-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200812_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='dislike', to='core.Entry'),
        ),
        migrations.AlterField(
            model_name='like',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to='core.Entry'),
        ),
    ]
