# Generated by Django 3.0.6 on 2020-10-04 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200814_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish'), ('deleted', 'deleted')], default='publish', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_type', models.CharField(choices=[('category', 'category'), ('title', 'title'), ('general', 'general')], default='general', max_length=40)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Suggested',
                'verbose_name_plural': 'Suggestions',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('publish', 'publish'), ('deleted', 'deleted'), ('morning', 'morning')], default='publish', max_length=25),
        ),
        migrations.AlterField(
            model_name='titlefollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_from_user_to_user'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('from_user', 'entry'), name='unique_from_user_entry'),
        ),
    ]
