# Generated by Django 3.0.6 on 2020-11-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20201004_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Bio'),
        ),
    ]
