# Generated by Django 3.0.6 on 2020-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_bio',
            field=models.BooleanField(default=True, verbose_name='Show Bio?'),
        ),
    ]
