# Generated by Django 3.0.6 on 2020-11-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_user_show_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggested',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Suggested', 'verbose_name_plural': 'Suggestions'},
        ),
    ]
