# Generated by Django 3.0.6 on 2020-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_notshowtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notshowtitle',
            options={},
        ),
        migrations.AddConstraint(
            model_name='notshowtitle',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='now_show_title_unique'),
        ),
    ]
