# Generated by Django 3.0.7 on 2020-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201128_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='a', max_length=50, upload_to='images/'),
            preserve_default=False,
        ),
    ]
