# Generated by Django 3.0.7 on 2020-12-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20201212_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('rookie', 'Rookie'), ('normal', 'Normal'), ('mod', 'Moderator')], default='rookie', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Birth day'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='city where you live'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_profile',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('uncertain', "I don't want to specify.")], default='uncertain', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='is_show_birth_day',
            field=models.BooleanField(default=False, verbose_name='Everyone to see'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_show_city',
            field=models.BooleanField(default=False, verbose_name='Everyone to see'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_show_gender',
            field=models.BooleanField(default=False, verbose_name='Everyone to see'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
