# Generated by Django 3.0.7 on 2020-12-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20201213_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('publish', 'publish'), ('publish_by_rookie', 'publish by rookie'), ('deleted', 'deleted'), ('morning', 'morning'), ('deleted_by_admin', 'deleted by admin')], default='publish', max_length=25),
        ),
    ]
