# Generated by Django 3.0.7 on 2020-12-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20201214_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Old ID'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('old_id',), name='old_id_unique'),
        ),
    ]
