# Generated by Django 3.0.7 on 2020-12-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20201213_1758'),
        ('core', '0051_auto_20201214_1939'),
    ]

    operations = [
    ]
