# Generated by Django 3.0.7 on 2020-12-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20201215_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='old_id_unique',
        ),
        migrations.AddField(
            model_name='title',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects', to='core.Title'),
        ),
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(default='d', max_length=140),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('slug',), name='slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(condition=models.Q(old_id__isnull=False), fields=('old_id',), name='title_old_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(old_id__isnull=False), fields=('old_id',), name='user_old_id_unique'),
        ),
    ]
