# Generated by Django 3.0.7 on 2020-12-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20201215_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AddField(
            model_name='entry',
            name='is_tematik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(old_id__isnull=False), fields=('old_id',), name='entry_old_id_unique'),
        ),
    ]
