# Generated by Django 3.0.7 on 2020-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20201215_1836'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['title', 'updated_at', 'status'], name='today_index'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['title', 'status'], name='total_index'),
        ),
    ]
