# Generated by Django 3.0.7 on 2020-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20201215_1922'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['status'], name='status_index'),
        ),
    ]
