# Generated by Django 3.0.7 on 2021-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20210110_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', through='core.Favorite', to='core.Entry'),
        ),
    ]
