# Generated by Django 3.0.7 on 2021-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20210418_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('like', 'like'), ('mention', 'mention'), ('info', 'info'), ('favorite', 'favorite'), ('username_title', 'username_title')], default='info', max_length=16),
        ),
    ]
