# Generated by Django 3.0.7 on 2021-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20210418_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='is_ukde',
            field=models.BooleanField(default=True),
        ),
    ]
