# Generated by Django 3.0.7 on 2021-05-26 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 39, 37, 234425, tzinfo=utc)),
        ),
    ]
