# Generated by Django 3.0.7 on 2021-05-26 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20210526_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 42, 3, 568839, tzinfo=utc)),
        ),
    ]
