# Generated by Django 3.0.7 on 2021-07-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210526_1145'),
        ('core', 'trigram_extension_migration'),
    ]

    operations = [
    ]
