# Generated by Django 3.0.7 on 2021-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20210713_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('like', 'like'), ('mention', 'mention'), ('info', 'info'), ('favorite', 'favorite'), ('username_title', 'username_title'), ('dislike', 'dislike')], default='info', max_length=16),
        ),
    ]
