# Generated by Django 3.0.7 on 2021-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20210825_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'follow'), ('like', 'like'), ('mention', 'mention'), ('info', 'info'), ('favorite', 'favorite'), ('username_title', 'username_title'), ('dislike', 'dislike'), ('info_title_entries', 'info_title_entries')], default='info', max_length=25),
        ),
    ]
