# Generated by Django 3.0.7 on 2021-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20210827_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='is_ukde',
            field=models.BooleanField(default=True),
        ),
    ]
