# Generated by Django 3.0.7 on 2021-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_useremotionactivities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('toxic', 'toxic'), ('error', 'error'), ('insult', 'insult'), ('undefined', 'undefined'), ('illegal', 'illegal'), ('dirtywords', 'dirty words')], max_length=48),
        ),
    ]
