# Generated by Django 3.0.7 on 2021-09-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20210905_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='count_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='count_favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='count_like',
            field=models.IntegerField(default=0),
        ),
    ]
