# Generated by Django 3.0.7 on 2021-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20210907_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremotionactivities',
            name='activity_type',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('favorite', 'favorite')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
