# Generated by Django 3.0.7 on 2021-09-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_useremotionactivities_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='is_deteled',
            field=models.BooleanField(default=False),
        ),
    ]
