# Generated by Django 3.0.7 on 2021-09-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20210917_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='is_deleted',
        ),
    ]
