# Generated by Django 3.0.7 on 2021-09-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20210925_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='punish_finish_date',
        ),
    ]
