# Generated by Django 3.0.7 on 2021-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_user_punish_finish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.AlterField(
            model_name='suggested',
            name='suggested_type',
            field=models.CharField(choices=[('title', 'title'), ('general', 'general')], default='general', max_length=40),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
