# Generated by Django 3.0.7 on 2022-02-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20210926_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=500, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('publish', 'publish'), ('publish_by_rookie', 'publish by rookie'), ('deleted', 'deleted'), ('morning', 'morning'), ('deleted_by_admin', 'deleted by admin')], default='publish', max_length=25, verbose_name='Statüs'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notshowtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='notshowtitle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notshowtitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='report',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.Entry', verbose_name='Girdi'),
        ),
        migrations.AlterField(
            model_name='report',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_report', to=settings.AUTH_USER_MODEL, verbose_name='Şikayet Eden'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('toxic', 'toxic'), ('error', 'error'), ('insult', 'insult'), ('undefined', 'undefined'), ('illegal', 'illegal'), ('dirtywords', 'dirty words')], max_length=48, verbose_name='Rapor Tipi'),
        ),
        migrations.AlterField(
            model_name='report',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_report', to=settings.AUTH_USER_MODEL, verbose_name='Şikayet Edilen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='title',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_ukde',
            field=models.BooleanField(default=True, verbose_name='Ukde mi?'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=400, unique=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='title',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='titlefollow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='titlefollow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='titlefollow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('rookie', 'Çaylak'), ('normal', 'Normal'), ('mod', 'Moderator')], default='rookie', max_length=25, verbose_name='Kullanıcı Tipi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=140, unique=True, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='useremotionactivities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='useremotionactivities',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='useremotionactivities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
    ]
