# Generated by Django 3.0.7 on 2022-02-16 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20220215_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bloklanan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_entry',
            field=models.BooleanField(default=True, verbose_name='Girdi'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_message',
            field=models.BooleanField(default=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to=settings.AUTH_USER_MODEL, verbose_name='Bloklayan Kullanıcı'),
        ),
    ]
