version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sozluk
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sozluk_db
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379 # for redis

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - backend-shell
    command: python manage.py runserver 0:8000
    restart: on-failure

    volumes:
      - .:/db

    ports:
      - "8000:8000"
    links:
      - db:db
      - redis:redis

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py rundramatiq
    volumes:
      - ..:/app
    depends_on:
      - web

  backend-shell:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: /app/docker/django.sh
    volumes:
      - ..:/app
    depends_on:
      - db

volumes:
    migrations:
        driver: local